//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CarTrackingModel", "VehicleGeoPoint", "Vehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CarTracking.Model.Vehicle), "GeoPoint", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CarTracking.Model.GeoPoint), true)]

#endregion

namespace CarTracking.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CarTrackingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CarTrackingEntities object using the connection string found in the 'CarTrackingEntities' section of the application configuration file.
        /// </summary>
        public CarTrackingEntities() : base("name=CarTrackingEntities", "CarTrackingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CarTrackingEntities object.
        /// </summary>
        public CarTrackingEntities(string connectionString) : base(connectionString, "CarTrackingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CarTrackingEntities object.
        /// </summary>
        public CarTrackingEntities(EntityConnection connection) : base(connection, "CarTrackingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GeoPoint> GeoPoints
        {
            get
            {
                if ((_GeoPoints == null))
                {
                    _GeoPoints = base.CreateObjectSet<GeoPoint>("GeoPoints");
                }
                return _GeoPoints;
            }
        }
        private ObjectSet<GeoPoint> _GeoPoints;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pin> Pins
        {
            get
            {
                if ((_Pins == null))
                {
                    _Pins = base.CreateObjectSet<Pin>("Pins");
                }
                return _Pins;
            }
        }
        private ObjectSet<Pin> _Pins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vehicle> Vehicles
        {
            get
            {
                if ((_Vehicles == null))
                {
                    _Vehicles = base.CreateObjectSet<Vehicle>("Vehicles");
                }
                return _Vehicles;
            }
        }
        private ObjectSet<Vehicle> _Vehicles;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GeoPoints EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGeoPoints(GeoPoint geoPoint)
        {
            base.AddObject("GeoPoints", geoPoint);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPins(Pin pin)
        {
            base.AddObject("Pins", pin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vehicles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVehicles(Vehicle vehicle)
        {
            base.AddObject("Vehicles", vehicle);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CarTrackingModel", Name="GeoPoint")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GeoPoint : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GeoPoint object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="deviceSn">Initial value of the DeviceSn property.</param>
        /// <param name="latitude">Initial value of the Latitude property.</param>
        /// <param name="heading">Initial value of the Heading property.</param>
        /// <param name="vehicleId">Initial value of the VehicleId property.</param>
        /// <param name="longitude">Initial value of the Longitude property.</param>
        public static GeoPoint CreateGeoPoint(global::System.Int32 id, global::System.String deviceSn, global::System.Decimal latitude, global::System.Int32 heading, global::System.Int32 vehicleId, global::System.Decimal longitude)
        {
            GeoPoint geoPoint = new GeoPoint();
            geoPoint.Id = id;
            geoPoint.DeviceSn = deviceSn;
            geoPoint.Latitude = latitude;
            geoPoint.Heading = heading;
            geoPoint.VehicleId = vehicleId;
            geoPoint.Longitude = longitude;
            return geoPoint;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DeviceSn
        {
            get
            {
                return _DeviceSn;
            }
            set
            {
                OnDeviceSnChanging(value);
                ReportPropertyChanging("DeviceSn");
                _DeviceSn = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DeviceSn");
                OnDeviceSnChanged();
            }
        }
        private global::System.String _DeviceSn;
        partial void OnDeviceSnChanging(global::System.String value);
        partial void OnDeviceSnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.Decimal _Latitude;
        partial void OnLatitudeChanging(global::System.Decimal value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Heading
        {
            get
            {
                return _Heading;
            }
            set
            {
                OnHeadingChanging(value);
                ReportPropertyChanging("Heading");
                _Heading = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Heading");
                OnHeadingChanged();
            }
        }
        private global::System.Int32 _Heading;
        partial void OnHeadingChanging(global::System.Int32 value);
        partial void OnHeadingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VehicleId
        {
            get
            {
                return _VehicleId;
            }
            set
            {
                OnVehicleIdChanging(value);
                ReportPropertyChanging("VehicleId");
                _VehicleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VehicleId");
                OnVehicleIdChanged();
            }
        }
        private global::System.Int32 _VehicleId;
        partial void OnVehicleIdChanging(global::System.Int32 value);
        partial void OnVehicleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GeopointId
        {
            get
            {
                return _GeopointId;
            }
            set
            {
                OnGeopointIdChanging(value);
                ReportPropertyChanging("GeopointId");
                _GeopointId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GeopointId");
                OnGeopointIdChanged();
            }
        }
        private Nullable<global::System.Int32> _GeopointId;
        partial void OnGeopointIdChanging(Nullable<global::System.Int32> value);
        partial void OnGeopointIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.Decimal _Longitude;
        partial void OnLongitudeChanging(global::System.Decimal value);
        partial void OnLongitudeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CarTrackingModel", "VehicleGeoPoint", "Vehicle")]
        public Vehicle Vehicle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("CarTrackingModel.VehicleGeoPoint", "Vehicle").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("CarTrackingModel.VehicleGeoPoint", "Vehicle").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vehicle> VehicleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("CarTrackingModel.VehicleGeoPoint", "Vehicle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vehicle>("CarTrackingModel.VehicleGeoPoint", "Vehicle", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CarTrackingModel", Name="Pin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pin object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="pinName">Initial value of the PinName property.</param>
        /// <param name="latitude">Initial value of the Latitude property.</param>
        /// <param name="longitude">Initial value of the Longitude property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        public static Pin CreatePin(global::System.Int32 id, global::System.String pinName, global::System.Decimal latitude, global::System.Decimal longitude, global::System.DateTime createdDate)
        {
            Pin pin = new Pin();
            pin.Id = id;
            pin.PinName = pinName;
            pin.Latitude = latitude;
            pin.Longitude = longitude;
            pin.CreatedDate = createdDate;
            return pin;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PinName
        {
            get
            {
                return _PinName;
            }
            set
            {
                OnPinNameChanging(value);
                ReportPropertyChanging("PinName");
                _PinName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PinName");
                OnPinNameChanged();
            }
        }
        private global::System.String _PinName;
        partial void OnPinNameChanging(global::System.String value);
        partial void OnPinNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.Decimal _Latitude;
        partial void OnLatitudeChanging(global::System.Decimal value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.Decimal _Longitude;
        partial void OnLongitudeChanging(global::System.Decimal value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CarTrackingModel", Name="Vehicle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vehicle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vehicle object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="licensePlate">Initial value of the LicensePlate property.</param>
        /// <param name="latitude">Initial value of the Latitude property.</param>
        /// <param name="deviceSn">Initial value of the DeviceSn property.</param>
        /// <param name="longitude">Initial value of the Longitude property.</param>
        public static Vehicle CreateVehicle(global::System.Int32 id, global::System.String licensePlate, global::System.Decimal latitude, global::System.String deviceSn, global::System.Decimal longitude)
        {
            Vehicle vehicle = new Vehicle();
            vehicle.Id = id;
            vehicle.LicensePlate = licensePlate;
            vehicle.Latitude = latitude;
            vehicle.DeviceSn = deviceSn;
            vehicle.Longitude = longitude;
            return vehicle;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LicensePlate
        {
            get
            {
                return _LicensePlate;
            }
            set
            {
                OnLicensePlateChanging(value);
                ReportPropertyChanging("LicensePlate");
                _LicensePlate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LicensePlate");
                OnLicensePlateChanged();
            }
        }
        private global::System.String _LicensePlate;
        partial void OnLicensePlateChanging(global::System.String value);
        partial void OnLicensePlateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.Decimal _Latitude;
        partial void OnLatitudeChanging(global::System.Decimal value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DeviceSn
        {
            get
            {
                return _DeviceSn;
            }
            set
            {
                OnDeviceSnChanging(value);
                ReportPropertyChanging("DeviceSn");
                _DeviceSn = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DeviceSn");
                OnDeviceSnChanged();
            }
        }
        private global::System.String _DeviceSn;
        partial void OnDeviceSnChanging(global::System.String value);
        partial void OnDeviceSnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.Decimal _Longitude;
        partial void OnLongitudeChanging(global::System.Decimal value);
        partial void OnLongitudeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CarTrackingModel", "VehicleGeoPoint", "GeoPoint")]
        public EntityCollection<GeoPoint> GeoPoints
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GeoPoint>("CarTrackingModel.VehicleGeoPoint", "GeoPoint");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GeoPoint>("CarTrackingModel.VehicleGeoPoint", "GeoPoint", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
